name: docker-release
on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - "master"
env:
  REGISTRY: docker.io
  IMAGE_NAME: rnanue

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: extract version
        id: extract_version
        run: | 
          VERSION=${GITHUB_REF#refs/tags/}
          echo "::set-output name=VERSION::$VERSION"

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          platforms: linux/amd64, linux/arm64
          push: true
          tags: cobirna/rnanue:${{ steps.extract_version.outputs.VERSION }}, cobirna/rnanue:latest

